In [ ]:
"""
Dictionaries in Python are mutable, unordered collections of key-value pairs ***INDEXING IS DONE THROUGH KEYS NOT BY INDEX***.
They are useful for storing data that can be retrieved using unique keys.
Each key-value pair is separated by a colon (:), and pairs are separated by commas.
Dictionaries are defined with curly braces {}.
keys-->unique
values-->single,multiple,duplicate datas can be added
"""

In [ ]:
"""
Keys:
Analogy: The catalog uses unique identifiers for each book, such as ISBN numbers or library codes.
Python Dictionary: In a Python dictionary,
#keys are like these unique identifiers.
#used inorder to extract element values
They allow you to look up a specific item in the dictionary.
"""

In [2]:
movie1={'title':'sachien','hero':'vijay','heroine':'jenelia'}
movie1

{'title': 'sachien', 'hero': 'vijay', 'heroine': 'jenelia'}

In [4]:
#to extract title
movie1['title']

'sachien'

In [2]:
#nested dictionaries
movie={'movie1':{'title':'sachin','hero':'vijay','heroin':'jenelia'},
       'movie2':{'title':'dragon','hero':'pradeep','heroin':'kayadu'}}
movie

{'movie1': {'title': 'sachin', 'hero': 'vijay', 'heroin': 'jenelia'},
 'movie2': {'title': 'dragon', 'hero': 'pradeep', 'heroin': 'kayadu'}}

In [4]:
movie['movie1']['title']

'sachin'

In [12]:
import pandas as pd
pd.DataFrame(movie) #to create a table form (combination of series)

         movie1   movie2
title    sachin   dragon
hero      vijay  pradeep
heroin  jenelia   kayadu

In [ ]:
movie={"hero":"ajith","heroin":"thrisha","music":"anirudh"}

In [ ]:
"""
Values:
Analogy: The actual details about each book, such as the book title, author, and publication year,
are stored in the catalog under each unique identifier.
Python Dictionary: In a Python dictionary, values are like these book details. They hold the information associated with each key.
"""

In [ ]:
dict1={"Title": "The Great Gatsby", "Author": "F. Scott Fitzgerald", "Year": 1925}

In [10]:
book1={"Title": "Harry Potter", "Author": "J.K.Rowling", "Year": 2010}

In [11]:
import pandas as pd
pd.Series(book1) #columns representation

Title     Harry Potter
Author     J.K.Rowling
Year              2010
dtype: object

In [3]:
library_catalog = {
    "978-3-16-148410-0": {"Title": "The Great Gatsby", "Author": "F. Scott Fitzgerald", "Year": 1925},
    "978-1-86197-876-9": {"Title": "To Kill a Mockingbird", "Author": "Harper Lee", "Year": 1960},
    "978-0-452-28423-4": {"Title": "1984", "Author": "George Orwell", "Year": 1949}
}

In [4]:
pd.DataFrame(library_catalog)

          978-3-16-148410-0      978-1-86197-876-9 978-0-452-28423-4
Title      The Great Gatsby  To Kill a Mockingbird              1984
Author  F. Scott Fitzgerald             Harper Lee     George Orwell
Year                   1925                   1960              1949

In [ ]:
"""
Keys: The ISBN numbers ("978-3-16-148410-0", "978-1-86197-876-9", "978-0-452-28423-4") are the unique identifiers (keys) for each book.
Values: The dictionaries associated with each ISBN contain the book's details (title, author, year).
These are the values in the main dictionary.
"""